### ISSUE TITLE
Command Line Useage

### ISSUE THREAD

**Issue by imichaelnorris** [samanthasiow/639-final-project#3]
I'm writing this down just in case I get amnesia (and I like checkboxes)

The main way to use the CLI is probably gonna be

```
$ python cli.py gene1.fa subsequence.fa
```

Or if the subsequence is small:

```
$ python cli.py gene1.fa GCAGAC
```

Or if you want to search through multiple genes:

```
$ python cli.py gene1.fa gene2.fa gene3.fa ... GCAGC
```

I'm not sure if there's a better way to list, say 100 genes.  Maybe we can have a flag for an input file which has one line per file that contains a gene?  Or maybe all the genes should be in the same fasta file.
## TODO
- [ ] --algorithm flag with options "nlogn", "nlogm", "boyermoore"
- [ ] CLI for single genome and single subsequence
  - [ ] CLI for n log n algo
  - [ ] CLI for n log m algo
  - [ ] CLI for Boyer Moore
- [ ] CLI for multiple genome and single subsequence
  - [ ] CLI for n \* n log n algo
  - [ ] CLI for n \* n log m algo

**Comment by samanthasiow** [comment]
We could also add an arg to choose which algorithm to use.
e.g. `python cli.py --algorithm nlogn gene1.fa subsequence.fa`

Where nlogn can be replaced with nlogm/naive/boyermoore.

**Comment by samanthasiow** [comment]
Also, sub-issue within this issue that was fixed: made your issue nice and pretty with Markdown.

**Comment by imichaelnorris** [comment]
+1 to markdown, thanks.

Also, to the first point, I agree there should be a --algorithm flag.
